package vistas;

import controllers.CategoryController;
import controllers.ProductController;
import entities.Product;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saske
 */
public class App extends javax.swing.JDialog implements Messages{

    /**
     * Creates new form App
     */
    public App(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JPanel();
        jlName = new javax.swing.JLabel();
        jlNow = new javax.swing.JLabel();
        jbHome = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        jbSearchByCategory = new javax.swing.JButton();
        jbSearchByPattern = new javax.swing.JButton();
        jcbCategory = new javax.swing.JComboBox<>();
        jtfPattern = new javax.swing.JTextField();
        jScrollProducts = new javax.swing.JScrollPane();
        jtableProducts = new javax.swing.JTable();
        jlAddProduct = new javax.swing.JLabel();
        jlException = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuBar.setBackground(new java.awt.Color(20, 208, 208));
        menuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menuBar.add(jlName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, -1, -1));
        menuBar.add(jlNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jbHome.setBackground(new java.awt.Color(255, 255, 255));
        jbHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Saske\\Documents\\Proyectos\\LaPaleta\\icons\\home.png")); // NOI18N
        jbHome.setBorder(null);
        jbHome.setBorderPainted(false);
        jbHome.setContentAreaFilled(false);
        jbHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHomeActionPerformed(evt);
            }
        });
        menuBar.add(jbHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 38, 31));

        getContentPane().add(menuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 663, 34));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setMaximumSize(new java.awt.Dimension(659, 442));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbSearchByCategory.setIcon(new javax.swing.ImageIcon("C:\\Users\\Saske\\Documents\\Proyectos\\LaPaleta\\icons\\search.png")); // NOI18N
        jbSearchByCategory.setContentAreaFilled(false);
        jbSearchByCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSearchByCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchByCategoryActionPerformed(evt);
            }
        });
        content.add(jbSearchByCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 29, 29));

        jbSearchByPattern.setIcon(new javax.swing.ImageIcon("C:\\Users\\Saske\\Documents\\Proyectos\\LaPaleta\\icons\\search.png")); // NOI18N
        jbSearchByPattern.setContentAreaFilled(false);
        jbSearchByPattern.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSearchByPattern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchByPatternActionPerformed(evt);
            }
        });
        content.add(jbSearchByPattern, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 29, 29));

        jcbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {CategoryController.getCategory(1).getName(),CategoryController.getCategory(2).getName(),CategoryController.getCategory(3).getName()}));
        jcbCategory.setLightWeightPopupEnabled(false);
        content.add(jcbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 460, 29));

        jtfPattern.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPatternKeyReleased(evt);
            }
        });
        content.add(jtfPattern, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 460, 29));

        jtableProducts.setModel(new vistas.ProductTableModel(ProductController.getProducts(1, 15)));
        jtableProducts.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtableProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtableProducts.setRowHeight(20);
        jtableProducts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtableProducts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtableProducts.getTableHeader().setResizingAllowed(false);
        jtableProducts.getTableHeader().setReorderingAllowed(false);
        jtableProducts.setVerifyInputWhenFocusTarget(false);
        jtableProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableProductsMouseClicked(evt);
            }
        });
        jScrollProducts.setViewportView(jtableProducts);

        content.add(jScrollProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 589, 285));

        jlAddProduct.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jlAddProduct.setText("+");
        jlAddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlAddProductMouseClicked(evt);
            }
        });
        content.add(jlAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 17));

        jlException.setForeground(new java.awt.Color(255, 0, 0));
        content.add(jlException, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 20));

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 663, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbHomeActionPerformed

    private void jlAddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAddProductMouseClicked
        AddProduct addProduct = new AddProduct(this, true);
        addProduct.setVisible(true);
        addProduct.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        DefaultTableModel newModel = (DefaultTableModel) jtableProducts.getModel();
        Object nuevo[] = {1,2,3,4,5,6};
        newModel.addRow(nuevo);
    }//GEN-LAST:event_jlAddProductMouseClicked

    private void jbSearchByPatternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchByPatternActionPerformed
        String pattern = jtfPattern.getText();
        try {
            if(pattern.length() == 0) throw new Exception("EMPTY_INPUT");
        } catch(Exception e) {
            jtfPattern.setBorder(BORDER_EXCEPTION);
            jlException.setText(EMPTY_INPUT);
            jlException.setVisible(true);
            System.out.println("App.java says -> " + e);
            return;
        }
        ArrayList<Product> products = ProductController.search(pattern);
        jtableProducts.setModel(new ProductTableModel(products));
    }//GEN-LAST:event_jbSearchByPatternActionPerformed

    private void jtfPatternKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPatternKeyReleased
        jtfPattern.setBorder(BORDER);
        jlException.setVisible(false);
    }//GEN-LAST:event_jtfPatternKeyReleased

    private void jbSearchByCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchByCategoryActionPerformed
        ArrayList<Product> products = ProductController.findByCategory(jcbCategory.getSelectedIndex()+1);
        jtableProducts.setModel(new ProductTableModel(products));
    }//GEN-LAST:event_jbSearchByCategoryActionPerformed

    private void jtableProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableProductsMouseClicked
        int row = jtableProducts.getSelectedRow();
        int index = Integer.valueOf(jtableProducts.getValueAt(row, 0).toString());
        Product productToManipulate = ProductController.get(index);
        EditAndDelete editAndDelete = new EditAndDelete(this, true, productToManipulate);
        editAndDelete.setVisible(true);
        editAndDelete.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jtableProductsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                App dialog = new App(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JScrollPane jScrollProducts;
    private javax.swing.JButton jbHome;
    private javax.swing.JButton jbSearchByCategory;
    private javax.swing.JButton jbSearchByPattern;
    private javax.swing.JComboBox<String> jcbCategory;
    private javax.swing.JLabel jlAddProduct;
    private javax.swing.JLabel jlException;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlNow;
    private javax.swing.JTable jtableProducts;
    private javax.swing.JTextField jtfPattern;
    private javax.swing.JPanel menuBar;
    // End of variables declaration//GEN-END:variables
}
