package vistas;

/**
 *
 * @author Saske
 */
public class App extends javax.swing.JDialog {

    /**
     * Creates new form Producto
     */
    public App(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JPanel();
        jlName = new javax.swing.JLabel();
        jlNow = new javax.swing.JLabel();
        jbHome = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        jbSearchxProductName = new javax.swing.JButton();
        jbSearchxProductCategory = new javax.swing.JButton();
        jcbProductCategories = new javax.swing.JComboBox<>();
        jtfProductName = new javax.swing.JTextField();
        jScrollProducts = new javax.swing.JScrollPane();
        jtableProducts = new javax.swing.JTable();
        jlAddProduct = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        menuBar.setBackground(new java.awt.Color(20, 208, 208));

        jbHome.setBackground(new java.awt.Color(255, 255, 255));
        jbHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Saske\\Documents\\Proyectos\\LaPaleta\\icons\\home.png")); // NOI18N
        jbHome.setBorder(null);
        jbHome.setBorderPainted(false);
        jbHome.setContentAreaFilled(false);
        jbHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addComponent(jlNow)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addContainerGap(309, Short.MAX_VALUE)
                .addComponent(jbHome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
            .addGroup(menuBarLayout.createSequentialGroup()
                .addComponent(jlName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addComponent(jlNow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbHome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlName)
                .addGap(8, 8, 8))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));

        jbSearchxProductName.setIcon(new javax.swing.ImageIcon("C:\\Users\\Saske\\Documents\\Proyectos\\LaPaleta\\icons\\search.png")); // NOI18N
        jbSearchxProductName.setContentAreaFilled(false);
        jbSearchxProductName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbSearchxProductCategory.setIcon(new javax.swing.ImageIcon("C:\\Users\\Saske\\Documents\\Proyectos\\LaPaleta\\icons\\search.png")); // NOI18N
        jbSearchxProductCategory.setContentAreaFilled(false);
        jbSearchxProductCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSearchxProductCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchxProductCategoryActionPerformed(evt);
            }
        });

        jcbProductCategories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbProductCategories.setLightWeightPopupEnabled(false);

        jtfProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfProductNameActionPerformed(evt);
            }
        });

        jtableProducts.setModel(new vistas.ProductTableModel());
        jtableProducts.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtableProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtableProducts.setRowHeight(20);
        jtableProducts.getTableHeader().setResizingAllowed(false);
        jtableProducts.getTableHeader().setReorderingAllowed(false);
        jtableProducts.setVerifyInputWhenFocusTarget(false);
        jtableProducts.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jtableProductsComponentResized(evt);
            }
        });
        jScrollProducts.setViewportView(jtableProducts);

        jlAddProduct.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jlAddProduct.setText("+");
        jlAddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlAddProductMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jbSearchxProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbSearchxProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfProductName)
                            .addComponent(jcbProductCategories, 0, 460, Short.MAX_VALUE)))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlAddProduct)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtfProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSearchxProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbSearchxProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbProductCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbHomeActionPerformed

    private void jbSearchxProductCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchxProductCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSearchxProductCategoryActionPerformed

    private void jtfProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfProductNameActionPerformed

    private void jtableProductsComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jtableProductsComponentResized
        
    }//GEN-LAST:event_jtableProductsComponentResized

    private void jlAddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAddProductMouseClicked
        System.out.println("Button Clicked");
    }//GEN-LAST:event_jlAddProductMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                App dialog = new App(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JScrollPane jScrollProducts;
    private javax.swing.JButton jbHome;
    private javax.swing.JButton jbSearchxProductCategory;
    private javax.swing.JButton jbSearchxProductName;
    private javax.swing.JComboBox<String> jcbProductCategories;
    private javax.swing.JLabel jlAddProduct;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlNow;
    private javax.swing.JTable jtableProducts;
    private javax.swing.JTextField jtfProductName;
    private javax.swing.JPanel menuBar;
    // End of variables declaration//GEN-END:variables
}
