package vistas;

import controllers.CategoryController;
import controllers.ProductController;
import entities.Product;
import java.awt.Component;
import javax.swing.JTable;
import static vistas.Messages.BORDER_EXCEPTION;
import static vistas.Messages.EMPTY_INPUT;
import static vistas.Messages.INVALID_INPUT;

/**
 *
 * @author Saske
 */
public class EditAndDelete extends javax.swing.JDialog implements Messages {
    
    private Product productToManipulate;
    
    /**
     * Creates new form EditAndDelete
     */
    public EditAndDelete(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public EditAndDelete(javax.swing.JDialog parent, boolean modal, Product product){
        super(parent, modal);
        initComponents();
        productToManipulate = product;
        jlbProductId.setText(Integer.toString(product.getProductId()));
        jlbException.setVisible(false);
        jtfName.setText(product.getName());
        jtfAlias.setText(product.getAlias());
        jtfPrice.setText(Double.toString(product.getPrice()));
        jcbCategories.setSelectedIndex(product.getCategoryId() - 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jlbProductIdField = new javax.swing.JLabel();
        jlbProductId = new javax.swing.JLabel();
        jlbName = new javax.swing.JLabel();
        jlbPrice = new javax.swing.JLabel();
        jlbAlias = new javax.swing.JLabel();
        jcbCategories = new javax.swing.JComboBox<>();
        jlbCategory = new javax.swing.JLabel();
        jtfAlias = new javax.swing.JTextField();
        jtfPrice = new javax.swing.JTextField();
        jtfName = new javax.swing.JTextField();
        jbttAccept = new javax.swing.JButton();
        jbttCancel = new javax.swing.JButton();
        jbttDelete = new javax.swing.JButton();
        jlbException = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbProductIdField.setText("Clave");
        content.add(jlbProductIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 20));
        content.add(jlbProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, 20));

        jlbName.setText("Nombre");
        content.add(jlbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jlbPrice.setText("Precio");
        content.add(jlbPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jlbAlias.setText("Alias");
        content.add(jlbAlias, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jcbCategories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {CategoryController.getCategory(1).getName(),CategoryController.getCategory(2).getName(),CategoryController.getCategory(3).getName()}));
        content.add(jcbCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 190, -1));

        jlbCategory.setText("Categoria");
        content.add(jlbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jtfAlias.setText("jTextField1");
        content.add(jtfAlias, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 190, -1));

        jtfPrice.setText("jTextField2");
        jtfPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPriceKeyReleased(evt);
            }
        });
        content.add(jtfPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 190, -1));

        jtfName.setText("jTextField3");
        content.add(jtfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 190, -1));

        jbttAccept.setText("Aceptar");
        jbttAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttAcceptActionPerformed(evt);
            }
        });
        content.add(jbttAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jbttCancel.setText("Cancelar");
        jbttCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttCancelActionPerformed(evt);
            }
        });
        content.add(jbttCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        jbttDelete.setText("Eliminar");
        jbttDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttDeleteActionPerformed(evt);
            }
        });
        content.add(jbttDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jlbException.setForeground(new java.awt.Color(255, 0, 0));
        content.add(jlbException, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 20));

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbttCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbttCancelActionPerformed

    private void jbttAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttAcceptActionPerformed
        try {
            String name = jtfName.getText();
            String alias = jtfAlias.getText();
            
            if(name.length() == 0 || alias.length() == 0){
                throw new Exception("EMPTY_INPUT");
            }
            
            int index = productToManipulate.getProductId();
            int inventoryId = productToManipulate.getInventoryId();
            Double price = Double.valueOf(jtfPrice.getText());
            
            Product newProduct = new Product(index, name, price, alias, inventoryId,jcbCategories.getSelectedIndex()+1);
            ProductController.update(index, newProduct);
        } catch (NumberFormatException e) {
            jlbException.setVisible(true);
            jlbException.setText(INVALID_INPUT);
            jtfPrice.setBorder(BORDER_EXCEPTION);
            System.out.println("EditAndDelete.java says -> " + e);
            return;
        } catch (Exception ex) {
            jlbException.setVisible(true);
            jlbException.setText(EMPTY_INPUT);
            System.out.println("EditAndDelete.java says -> " + ex);
            return;
        }
        this.dispose();
    }//GEN-LAST:event_jbttAcceptActionPerformed

    private void jtfPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPriceKeyReleased
        jtfPrice.setBorder(BORDER);
        jlbException.setVisible(false);
    }//GEN-LAST:event_jtfPriceKeyReleased

    private void jbttDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttDeleteActionPerformed
        ProductController.delete(productToManipulate.getProductId());
        this.dispose();
    }//GEN-LAST:event_jbttDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditAndDelete dialog = new EditAndDelete(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JButton jbttAccept;
    private javax.swing.JButton jbttCancel;
    private javax.swing.JButton jbttDelete;
    private javax.swing.JComboBox<String> jcbCategories;
    private javax.swing.JLabel jlbAlias;
    private javax.swing.JLabel jlbCategory;
    private javax.swing.JLabel jlbException;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbPrice;
    private javax.swing.JLabel jlbProductId;
    private javax.swing.JLabel jlbProductIdField;
    private javax.swing.JTextField jtfAlias;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfPrice;
    // End of variables declaration//GEN-END:variables
}
