package vistas;

import conexionDB.ConnectionToLapaletadb;
import java.sql.*;
import javax.swing.JDialog;

/**
 *
 * @author Saske
 */
public class Login extends javax.swing.JFrame implements Messages{ 
    
    /**
     * Creates new form Inicio
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jlPlaceholderUser = new javax.swing.JLabel();
        jlPlaceholderPassword = new javax.swing.JLabel();
        jlTitle = new javax.swing.JLabel();
        jlTittle = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jpfPassword = new javax.swing.JPasswordField();
        jbInicio = new javax.swing.JButton();
        jlExcepcion = new javax.swing.JLabel();
        title = new javax.swing.JPanel();
        jlTitleOne = new javax.swing.JLabel();
        jlTitleTwo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(731, 409));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(350, 392));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlPlaceholderUser.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        jlPlaceholderUser.setForeground(new java.awt.Color(204, 204, 204));
        jlPlaceholderUser.setText(" Usuario");
        content.add(jlPlaceholderUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 140, 185, 33));

        jlPlaceholderPassword.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        jlPlaceholderPassword.setForeground(new java.awt.Color(204, 204, 204));
        jlPlaceholderPassword.setText(" Contraseña");
        content.add(jlPlaceholderPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 203, 185, 33));

        jlTitle.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jlTitle.setText("Bienvenido");
        content.add(jlTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 70, -1, -1));

        jlTittle.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jlTittle.setForeground(new java.awt.Color(102, 255, 255));
        jlTittle.setText("Paletero");
        content.add(jlTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 70, -1, -1));

        jtfUsername.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        jtfUsername.setForeground(new java.awt.Color(102, 102, 102));
        jtfUsername.setBorder(BORDER);
        jtfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfUsernameKeyReleased(evt);
            }
        });
        content.add(jtfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 140, 185, 33));

        jpfPassword.setBorder(BORDER);
        jpfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfPasswordActionPerformed(evt);
            }
        });
        jpfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpfPasswordKeyReleased(evt);
            }
        });
        content.add(jpfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 203, 185, 33));

        jbInicio.setBackground(new java.awt.Color(0, 204, 204));
        jbInicio.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jbInicio.setForeground(new java.awt.Color(255, 255, 255));
        jbInicio.setText("Iniciar Sesión");
        jbInicio.setBorderPainted(false);
        jbInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbInicioMouseClicked(evt);
            }
        });
        jbInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInicioActionPerformed(evt);
            }
        });
        content.add(jbInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 289, -1, -1));

        jlExcepcion.setForeground(new java.awt.Color(255, 0, 0));
        content.add(jlExcepcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, 20));
        jlExcepcion.setVisible(false);

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 381, 409));

        title.setBackground(new java.awt.Color(255, 153, 255));

        jlTitleOne.setFont(new java.awt.Font("Open Sans Semibold", 0, 36)); // NOI18N
        jlTitleOne.setForeground(new java.awt.Color(255, 255, 255));
        jlTitleOne.setText("venta");

        jlTitleTwo.setFont(new java.awt.Font("Open Sans Semibold", 0, 36)); // NOI18N
        jlTitleTwo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitleTwo.setText("Sistema punto de");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jlTitleOne)
                    .addComponent(jlTitleTwo))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jlTitleTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlTitleOne, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 409));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInicioActionPerformed
        String username = jtfUsername.getText().trim();
        char password[] = jpfPassword.getPassword();
        byte flujo = 0;
        
        if(username.isEmpty()) flujo += 1;
        if(password.length == 0) flujo += 2;
        
        if(flujo > 0){
            jlExcepcion.setText(EMPTY_INPUT);
            jlExcepcion.setVisible(true);
            
            switch (flujo) {
                case 1 -> jtfUsername.setBorder(BORDER_EXCEPTION);
                case 2 -> jpfPassword.setBorder(BORDER_EXCEPTION);
                case 3 -> {
                    jtfUsername.setBorder(BORDER_EXCEPTION);
                    jpfPassword.setBorder(BORDER_EXCEPTION);
                }
            }
            return;
        }
         
        try {
            ConnectionToLapaletadb consulta = new ConnectionToLapaletadb();
            String statement = "SELECT * FROM usuario WHERE uUsuario = '{?}' ";
            statement = statement.replace("{?}", username);
            ResultSet rs = consulta.executeQuery(statement);
            
            if (!rs.next()) {
                jlExcepcion.setText(ERROR_LOGIN);
                jlExcepcion.setVisible(true);
                return;
            }
            
            String realPassword = rs.getString("uContraseña");
                
            for (int i = 0; i < password.length; i++) {
                if(password[i] != realPassword.charAt(i)){
                    jlExcepcion.setText(ERROR_LOGIN);
                    jlExcepcion.setVisible(true);
                    return;
                }
            }
            
            App app = new App(this, false);
            this.setVisible(false);
            app.setVisible(true);
            app.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            this.setVisible(true);
            
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jbInicioActionPerformed

    private void jbInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbInicioMouseClicked

    }//GEN-LAST:event_jbInicioMouseClicked

    private void jpfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfPasswordActionPerformed

    private void jtfUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUsernameKeyReleased
        jlPlaceholderUser.setVisible(false);
        jtfUsername.setBorder(BORDER);
        jlExcepcion.setVisible(false);
    }//GEN-LAST:event_jtfUsernameKeyReleased

    private void jpfPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfPasswordKeyReleased
        jlPlaceholderPassword.setVisible(false);
        jpfPassword.setBorder(BORDER);
        jlExcepcion.setVisible(false);
    }//GEN-LAST:event_jpfPasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JButton jbInicio;
    private javax.swing.JLabel jlExcepcion;
    private javax.swing.JLabel jlPlaceholderPassword;
    private javax.swing.JLabel jlPlaceholderUser;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JLabel jlTitleOne;
    private javax.swing.JLabel jlTitleTwo;
    private javax.swing.JLabel jlTittle;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextField jtfUsername;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables
}
