package views;

import controllers.CategoryController;
import controllers.ProductController;
import entities.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author Saske
 */
public class AddProduct extends javax.swing.JDialog implements Messages {
    
    private static final int OK = 1;
    private static final int PRICE_INVALID = 2;
    private static final int EMPTIES = 3;
    
    /**
     * Creates new form AddProduct from a Frame
     */
    public AddProduct(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jlbException.setVisible(false);
        setLocationRelativeTo(parent);
    }
    
    /**
     * Creates new form AddProduct from a JDialog.
     */
    public AddProduct(javax.swing.JDialog parent, boolean modal){
        super(parent, modal);
        initComponents();
        jlbException.setVisible(false);
        setLocationRelativeTo(parent);
    }
    
    /**
     * Return a int that represents if the fields are ok, empties, 
     * or just price input is invalid.
     */
    private int getFieldStatus(){
        if(jtfName.getText().isEmpty() || jtfAlias.getText().isEmpty() || jtfPrice.getText().isEmpty()) return EMPTIES;
        
        try {
            Double.valueOf(jtfPrice.getText());
        } catch (NumberFormatException e) {
            return PRICE_INVALID;
        }
        
        return OK;
    }
    
    /**
     * Show the exception to User dependig on the status fields.
     */
    private void showException(int status){
        if(status == EMPTIES){
            jlbException.setText(EMPTY_INPUT);
            jlbException.setVisible(true);
            return;
        }
        
        if(status == PRICE_INVALID){
            jlbException.setText(INVALID_INPUT);
            jlbException.setVisible(true);
            jtfPrice.setBorder(BORDER_EXCEPTION);
        }
    }
    
    private void cleanInputs(){
        jtfName.setText("");
        jtfAlias.setText("");
        jtfPrice.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jlblName = new javax.swing.JLabel();
        jlbPrice = new javax.swing.JLabel();
        jlbAlias = new javax.swing.JLabel();
        jlbCategory = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jtfPrice = new javax.swing.JTextField();
        jtfAlias = new javax.swing.JTextField();
        jcbCategories = new javax.swing.JComboBox<>();
        jBttAccept = new javax.swing.JButton();
        jBttCancel = new javax.swing.JButton();
        jlbException = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo producto");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlblName.setText("Nombre");
        content.add(jlblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jlbPrice.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlbPrice.setText("Precio");
        content.add(jlbPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jlbAlias.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlbAlias.setText("Alias");
        content.add(jlbAlias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jlbCategory.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlbCategory.setText("Categoria");
        content.add(jlbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        content.add(jtfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 140, -1));

        jtfPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPriceKeyReleased(evt);
            }
        });
        content.add(jtfPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 140, -1));
        content.add(jtfAlias, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 140, -1));

        jcbCategories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {CategoryController.getCategory(1).getName(),CategoryController.getCategory(2).getName(),CategoryController.getCategory(3).getName()}));
        content.add(jcbCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 140, -1));

        jBttAccept.setBackground(new java.awt.Color(122, 204, 30));
        jBttAccept.setText("Aceptar");
        jBttAccept.setBorderPainted(false);
        jBttAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttAcceptActionPerformed(evt);
            }
        });
        content.add(jBttAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jBttCancel.setBackground(new java.awt.Color(255, 51, 51));
        jBttCancel.setText("Cancelar");
        jBttCancel.setBorderPainted(false);
        jBttCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttCancelActionPerformed(evt);
            }
        });
        content.add(jBttCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        jlbException.setForeground(new java.awt.Color(255, 0, 0));
        jlbException.setText("");
        jlbException.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        content.add(jlbException, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));
        jlbException.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttAcceptActionPerformed
        if(getFieldStatus() != OK){
            showException(getFieldStatus());
            return;
        } 
        
        if(JOptionPane.showConfirmDialog(this, "¿Está seguro?") != JOptionPane.OK_OPTION) return;
        
        String name = jtfName.getText();
        String alias = jtfAlias.getText();
        Double price = Double.valueOf(jtfPrice.getText());

        Product newProduct = new Product(name, price, alias, jcbCategories.getSelectedIndex() + 1);
        ProductController.add(newProduct);
        cleanInputs();
    }//GEN-LAST:event_jBttAcceptActionPerformed

    private void jBttCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBttCancelActionPerformed

    private void jtfPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPriceKeyReleased
        jtfPrice.setBorder(BORDER);
        jlbException.setVisible(false);
    }//GEN-LAST:event_jtfPriceKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddProduct dialog = new AddProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JButton jBttAccept;
    private javax.swing.JButton jBttCancel;
    private javax.swing.JComboBox<String> jcbCategories;
    private javax.swing.JLabel jlbAlias;
    private javax.swing.JLabel jlbCategory;
    private javax.swing.JLabel jlbException;
    private javax.swing.JLabel jlbPrice;
    private javax.swing.JLabel jlblName;
    private javax.swing.JTextField jtfAlias;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfPrice;
    // End of variables declaration//GEN-END:variables
}
