package views;

import conexionDB.ConnectionToLapaletadb;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.sql.*;
import javax.swing.JDialog;

/**
 *
 * @author Saske
 */
public class Login extends javax.swing.JFrame implements Messages{ 
    
    private static final int FIELDS_FILLED = 1;
    private static final int USERNAME_FIELD_EMPTY = 2;
    private static final int PASSWORD_FIELD_EMPTY = 3;
    private static final int FIELD_EMPTIES = 4;
    private static final int INVALID_CREDENTIALS = 5;
    
    /**
     * Creates new form Inicio
     */
    public Login() {
        initComponents();
        center();
    }
    
    /**
     * Center the Jframe relative to the monitor.
     */
    private void center(){
        Point center = GraphicsEnvironment.getLocalGraphicsEnvironment().getCenterPoint();
        int x = center.x - (getWidth()/2);
        int y = center.y - (getHeight()/2);
        center.move(x, y);
        setLocation(center);
    }
    
    /**
     * Return a int that represents if the fields are filled, empties, 
     * just username is empty or just  password is empty.
     */
    private int getFieldsStatus(){
        String username = jtfUsername.getText().trim();
        char password[] = jpfPassword.getPassword();
        
        if(username.isEmpty() && password.length == 0) return FIELD_EMPTIES;
        if(username.isEmpty()) return USERNAME_FIELD_EMPTY;
        if(password.length == 0) return PASSWORD_FIELD_EMPTY;
        
        return FIELDS_FILLED;
    }
    
    /**
     * Show the exception to User dependig on the status fields.
     */
    private void showException(int status){
        jlExcepcion.setText(EMPTY_INPUT);
        jlExcepcion.setVisible(true);
        
        if(status == USERNAME_FIELD_EMPTY){
            jtfUsername.setBorder(BORDER_EXCEPTION);
            return;
        }
        
        if(status == PASSWORD_FIELD_EMPTY){
            jpfPassword.setBorder(BORDER_EXCEPTION);
            return;
        }
        
        if(status == FIELD_EMPTIES) {
            jtfUsername.setBorder(BORDER_EXCEPTION);
            jpfPassword.setBorder(BORDER_EXCEPTION);
            return;
        }
        
        if(status == INVALID_CREDENTIALS){
            jlExcepcion.setText(ERROR_LOGIN);
            jlExcepcion.setVisible(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jlPlaceholderUser = new javax.swing.JLabel();
        jlPlaceholderPassword = new javax.swing.JLabel();
        jlTitle = new javax.swing.JLabel();
        jlTittle = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jpfPassword = new javax.swing.JPasswordField();
        jbLogin = new javax.swing.JButton();
        jlExcepcion = new javax.swing.JLabel();
        title = new javax.swing.JPanel();
        jlTitleOne = new javax.swing.JLabel();
        jlTitleTwo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(731, 409));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(350, 392));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlPlaceholderUser.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        jlPlaceholderUser.setForeground(new java.awt.Color(204, 204, 204));
        jlPlaceholderUser.setText(" Usuario");
        content.add(jlPlaceholderUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 185, 33));

        jlPlaceholderPassword.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        jlPlaceholderPassword.setForeground(new java.awt.Color(204, 204, 204));
        jlPlaceholderPassword.setText(" Contraseña");
        content.add(jlPlaceholderPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 185, 33));

        jlTitle.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jlTitle.setText("Bienvenido");
        content.add(jlTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jlTittle.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jlTittle.setForeground(new java.awt.Color(102, 255, 255));
        jlTittle.setText("Paletero");
        content.add(jlTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jtfUsername.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        jtfUsername.setForeground(new java.awt.Color(102, 102, 102));
        jtfUsername.setBorder(BORDER);
        jtfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfUsernameKeyReleased(evt);
            }
        });
        content.add(jtfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 185, 33));

        jpfPassword.setBorder(BORDER);
        jpfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpfPasswordKeyReleased(evt);
            }
        });
        content.add(jpfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 185, 33));

        jbLogin.setBackground(new java.awt.Color(0, 204, 204));
        jbLogin.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jbLogin.setForeground(new java.awt.Color(255, 255, 255));
        jbLogin.setText("Iniciar Sesión");
        jbLogin.setBorderPainted(false);
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });
        content.add(jbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jlExcepcion.setForeground(new java.awt.Color(255, 0, 0));
        content.add(jlExcepcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 20));
        jlExcepcion.setVisible(false);

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 310, 409));

        title.setBackground(new java.awt.Color(255, 153, 255));

        jlTitleOne.setFont(new java.awt.Font("Open Sans Semibold", 0, 36)); // NOI18N
        jlTitleOne.setForeground(new java.awt.Color(255, 255, 255));
        jlTitleOne.setText("venta");

        jlTitleTwo.setFont(new java.awt.Font("Open Sans Semibold", 0, 36)); // NOI18N
        jlTitleTwo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitleTwo.setText("Sistema punto de");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jlTitleOne)
                    .addComponent(jlTitleTwo))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jlTitleTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlTitleOne, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );

        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 409));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        String username = jtfUsername.getText().trim();
        char password[] = jpfPassword.getPassword();
        
        if(getFieldsStatus() != FIELDS_FILLED) {
            showException(getFieldsStatus());
            return;
        }
         
        ConnectionToLapaletadb cn = new ConnectionToLapaletadb();
        try {
            String statement = "SELECT * FROM usuario WHERE uUsuario = '{?}' ";
            statement = statement.replace("{?}", username);
            ResultSet usuario = cn.executeQuery(statement);
            
            if (!usuario.next()) {
                showException(INVALID_CREDENTIALS);
                return;
            }
            
            String realPassword = usuario.getString("uContraseña");
                
            for (int letra = 0; letra < password.length; letra++) {
                if(password[letra] != realPassword.charAt(letra)){
                    showException(INVALID_CREDENTIALS);
                    return;
                }
            }
            
            App app = new App(this, true);
            this.setVisible(false);
            app.setVisible(true);
            app.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            this.setVisible(true);
            
        } catch (SQLException e) {
            System.out.println("App.java says -> " + e);
        } finally {
            cn.close();
        }
    }//GEN-LAST:event_jbLoginActionPerformed

    private void jtfUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUsernameKeyReleased
        jlPlaceholderUser.setVisible(false);
        jtfUsername.setBorder(BORDER);
        jlExcepcion.setVisible(false);
    }//GEN-LAST:event_jtfUsernameKeyReleased

    private void jpfPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfPasswordKeyReleased
        jlPlaceholderPassword.setVisible(false);
        jpfPassword.setBorder(BORDER);
        jlExcepcion.setVisible(false);
    }//GEN-LAST:event_jpfPasswordKeyReleased

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JButton jbLogin;
    private javax.swing.JLabel jlExcepcion;
    private javax.swing.JLabel jlPlaceholderPassword;
    private javax.swing.JLabel jlPlaceholderUser;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JLabel jlTitleOne;
    private javax.swing.JLabel jlTitleTwo;
    private javax.swing.JLabel jlTittle;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextField jtfUsername;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables
}
